name: VPS 24/7 (Made by Deepak)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Root User
        run: |
          echo "root:root" | sudo chpasswd
          sudo sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo systemctl restart ssh

      - name: Run VPS with SSHX (Loop)
        run: |
          while true; do
            echo "🔗 Starting new sshx tunnel..."
            curl -sSf https://sshx.io/get | sh -s run &
            sleep 6
          done
